version: '3'
services:
  dev:
    container_name: dev_environment
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mariadb
    privileged: true
    volumes:
      - ../workspace:/home/developer/workspace:delegated
      - /dev/bus/usb:/dev/bus/usb:delegated
    command: sleep infinity
    ports:
      - "3000:3000"
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: dev_environment_db
    volumes:
      - dev_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
volumes:
  dev_db_data: